#!/usr/bin/env node
// scripts/quartz_prepare.js
// Prepare a minimal Quartz-compatible vault from the app's JSON DB files.

const fs = require('fs');
const path = require('path');

const ROOT = process.cwd();
const DB_DIR = path.join(ROOT, 'data', 'jsondb');
const OUT_DIR = path.join(ROOT, 'quartz_vault');

function readJSON(name) {
  const p = path.join(DB_DIR, name + '.json');
  if (!fs.existsSync(p)) return [];
  const raw = fs.readFileSync(p, 'utf8');
  const cleaned = raw.replace(/^\uFEFF/, '').trim();
  try {
    return JSON.parse(cleaned);
  } catch (e) {
    console.error('Failed to parse', p, e.message);
    return [];
  }
}

function ensureDir(d) {
  if (!fs.existsSync(d)) fs.mkdirSync(d, { recursive: true });
}

function slugify(s) {
  return String(s).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

function writeFile(relPath, content) {
  const full = path.join(OUT_DIR, relPath);
  ensureDir(path.dirname(full));
  fs.writeFileSync(full, content, 'utf8');
  console.log('Wrote', relPath);
}

function buildTaskFiles() {
  const tasks = readJSON('tasks');
  tasks.forEach((t) => {
    const fname = `tasks/${slugify(t.title || t.id)}-${t.id}.md`;
    const front = [
      '---',
      `id: ${t.id}`,
      `title: "${(t.title || '').replace(/"/g, '\\"')}"`,
      `type: task`,
      `est_minutes: ${t.est_minutes || 0}`,
      `priority: ${t.priority || 0}`,
      `status: ${t.status || 'todo'}`,
      '---',
      '',
      `# ${t.title || t.id}`,
      '',
      t.description || '',
    ].join('\n');
    writeFile(fname, front);
  });
}

function buildDayplanFiles() {
  const plans = readJSON('dayplans');
  plans.forEach((p) => {
    const date = new Date(p.date).toISOString().split('T')[0];
    const fname = `dayplans/${date}-${p.id}.md`;
    const lines = [
      '---',
      `id: ${p.id}`,
      `date: ${p.date}`,
      'type: dayplan',
      '---',
      '',
      `# Dayplan ${date}`,
      '',
      '## Plan Items',
      '',
      ...(p.plan_items || []).map(pi => `- ${pi.action_text}`),
      ''
    ];
    writeFile(fname, lines.join('\n'));
  });
}

function buildJournalFiles() {
  // Build simple daily journal files from dayplans and tasks
  const plans = readJSON('dayplans');
  plans.forEach((p) => {
    const date = new Date(p.date).toISOString().split('T')[0];
    const fname = `journals/${date}-journal.md`;
    const tasks = readJSON('tasks');
    const related = (p.plan_items || []).map(pi => tasks.find(t => t.id === pi.task_id)).filter(Boolean);
    const lines = [
      '---',
      `date: ${date}`,
      'type: journal',
      'tags:',
      '  - daily-journal',
      '---',
      '',
      `# Daily Journal - ${date}`,
      '',
      '## Plan',
      '',
      ...(related.length ? related.map(t => `- [ ] ${t.title}`) : ['- No plan items']),
      '',
      '## Notes',
      '- Generated by local-ai-productivity for Quartz processing',
      ''
    ];
    writeFile(fname, lines.join('\n'));
  });
}

function main() {
  ensureDir(OUT_DIR);
  ensureDir(path.join(OUT_DIR, 'tasks'));
  ensureDir(path.join(OUT_DIR, 'dayplans'));
  ensureDir(path.join(OUT_DIR, 'journals'));

  buildTaskFiles();
  buildDayplanFiles();
  buildJournalFiles();

  console.log('Quartz vault prepared at', OUT_DIR);
}

main();
