const fs = require('fs');
const path = require('path');
const fetch = require('node-fetch');

function readJSONSafe(p) {
  if (!fs.existsSync(p)) return [];
  try { return JSON.parse(fs.readFileSync(p, 'utf8').replace(/^\uFEFF/, '').trim()); } catch(e) { return []; }
}

function slugify(s) {
  return String(s || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

function buildFiles(root) {
  const dbDir = path.join(root, 'data', 'jsondb');
  const tasks = readJSONSafe(path.join(dbDir, 'tasks.json'));
  const dayplans = readJSONSafe(path.join(dbDir, 'dayplans.json'));

  const out = [];

  tasks.forEach((t) => {
    const fname = `tasks/${slugify(t.title || t.id)}-${t.id}.md`;
    const front = [
      '---',
      `id: ${t.id}`,
      `title: "${(t.title || '').replace(/"/g, '\\"')}",`,
      `type: task`,
      `est_minutes: ${t.est_minutes || 0}`,
      `priority: ${t.priority || 0}`,
      `status: ${t.status || 'todo'}`,
      '---',
      '',
      `# ${t.title || t.id}`,
      '',
      t.description || '',
    ].join('\n');
    out.push({ path: fname, content: front });
  });

  dayplans.forEach((p) => {
    const date = new Date(p.date).toISOString().split('T')[0];
    const fname = `dayplans/${date}-${p.id}.md`;
    const lines = [
      '---',
      `id: ${p.id}`,
      `date: ${p.date}`,
      'type: dayplan',
      '---',
      '',
      `# Dayplan ${date}`,
      '',
      '## Plan Items',
      '',
      ...(p.plan_items || []).map(pi => `- ${pi.action_text}`),
      ''
    ];
    out.push({ path: fname, content: lines.join('\n') });
    // simple journal variant
    const jname = `journals/${date}-journal.md`;
    const related = (p.plan_items || []).map(pi => (tasks.find(t => t.id === pi.task_id))).filter(Boolean);
    const jlines = [
      '---',
      `date: ${date}`,
      'type: journal',
      'tags:',
      '  - daily-journal',
      '---',
      '',
      `# Daily Journal - ${date}`,
      '',
      '## Plan',
      '',
      ...(related.length ? related.map(t => `- [ ] ${t.title}`) : ['- No plan items']),
      '',
      '## Notes',
      '- Generated by local-ai-productivity',
      ''
    ];
    out.push({ path: jname, content: jlines.join('\n') });
  });

  return out;
}

function encodeBase64(text) {
  return Buffer.from(text, 'utf8').toString('base64');
}

async function getExistingSha(owner, repo, branch, pathp, token) {
  const resp = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${encodeURIComponent(pathp)}?ref=${encodeURIComponent(branch)}`, {
    headers: { Accept: 'application/vnd.github+json', Authorization: `Bearer ${token}` }
  });
  if (resp.status === 404) return null;
  if (!resp.ok) throw new Error(`GitHub lookup failed ${resp.status}`);
  const d = await resp.json();
  return d?.sha || null;
}

async function putFile(owner, repo, branch, pathp, content, token, message, sha) {
  const resp = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${encodeURIComponent(pathp)}`, {
    method: 'PUT',
    headers: { Accept: 'application/vnd.github+json', Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ message, content: encodeBase64(content), branch, ...(sha ? { sha } : {}) })
  });
  if (!resp.ok) {
    const detail = await resp.text();
    throw new Error(`PUT failed ${resp.status}: ${detail}`);
  }
  return resp.json();
}

module.exports = async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'POST required' });
  const { owner, repo, branch = 'main', token, pathPrefix = 'quartz_vault' } = req.body || {};
  if (!owner || !repo || !token) return res.status(400).json({ error: 'owner, repo, token required' });

  try {
    const files = buildFiles(process.cwd());
    const results = [];
    for (const f of files) {
      const targetPath = `${pathPrefix}/${f.path}`;
      const sha = await getExistingSha(owner, repo, branch, targetPath, token);
      const msg = sha ? `Update ${targetPath}` : `Create ${targetPath}`;
      const r = await putFile(owner, repo, branch, targetPath, f.content, token, msg, sha);
      results.push({ path: targetPath, commitSha: r?.commit?.sha });
    }
    return res.json({ ok: true, files: results });
  } catch (e) {
    console.error(e);
    return res.status(500).json({ error: e.message });
  }
};
